fun main() {
    try {
        day4Solution2()
    } catch (exception: Exception) {
        print("\n ${exception.stackTrace.contentToString()} \n")
    }
}